### PR TITLE
Added a camera toggle button

### PR DESCRIPTION
**Pull request by SilverFishCat**
Added a button to the top gui that toggles the camera frame on and off.
This change uses mod-gui, which is in <factorio directory>/data/core/lualib and is the recommended way to add ui on screen, so i used that.

### CODE REVIEW

**Comment by SilverFishCat** [comment]
actually i need to fix it

**Comment by SilverFishCat** [comment]
Fixed

**Comment by mitsuyoshi-yamazaki** [comment]
Thanks!

**Comment by mitsuyoshi-yamazaki** [comment]
memo

https://www.factorio.com/blog/post/fff-174

**Comment by mitsuyoshi-yamazaki** [comment]
@SilverFishCat Thanks for this PR, it works great!

One question: How can we initialize `global["toggle"]` and camera toggle button when loading a savedata with a previous version of Camera-san?
In the savedata, `global["toggle"] = {}` and `mod_gui.get_button_flow(player).add(...)` has never executed so the game will crash.

```
__Camera-san__/control.lua:140: attempt to index field 'toggle' (a nil value)
```

Any suggestions?

I tried:
- Initializing them in `on_load` event -> we can't change `global` variable in the event
- Writing a migration file that contains `global["toggle"] = {}` -> nothing changes (`attempt to index field 'toggle' (a nil value)`)
- Placing `global["toggle"] = {}` just below of `require "mod-gui"` -> nothing changes (`attempt to index field 'toggle' (a nil value)`)

**Comment by mitsuyoshi-yamazaki** [comment]
memo

> 7. control.lua script.on_configuration_changed()
>
> When mods are changed (prototypes added or removed), the major game version changes, a mod version changes, a mod is removed, or a mod is added the script.on_configuration_changed() event is fired for each mod subscribed to that event.
>
> This is the main place for handling mod internal data structure changes. Access to the global table, game table and game state are available and can be changed in any way seen fit by the mod.
>
> https://lua-api.factorio.com/latest/Data-Lifecycle.html

**Comment by SilverFishCat** [comment]
on_configuration_changed() will get called when you load an old save with an older version number of the mod, but it will also be called on every version change in the future. I think a more fitting solution is to use migrations. They are mentioned in https://lua-api.factorio.com/latest/Data-Lifecycle.html and explained a bit in https://lua-api.factorio.com/latest/Migrations.html . Migrations will only get called once of older saves.
Hope this helps!

**Comment by mitsuyoshi-yamazaki** [comment]
Thanks!

**Pull request merged**
